import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { stripTypeScriptTypes } from "node:module";
import test from "node:test";
import { runInNewContext, Script } from "node:vm";

const directory = new URL("../bitwig-controller/BeatTwin/", import.meta.url);
const sources = await Promise.all(["BeatTwin.control.ts", "midi.ts", "creative.ts"].map((name) => readFile(new URL(name, directory), "utf8")));
const combined = sources.join("\n\n");
const marker = "var midiProfileEnabled = false;";
const banner = "// GENERATED by scripts/build-bridge.ts; edit the TypeScript source.\n";

test("both generated profiles exactly match the single maintained source and modules", async () => {
  assert.equal(combined.split(marker).length, 2);
  for (const midi of [false, true]) {
    const filename = midi ? "BeatTwinMidi.control.js" : "BeatTwin.control.js";
    const expected = banner + stripTypeScriptTypes(midi ? combined.replace(marker, "var midiProfileEnabled = true;") : combined).replace(/[\t ]+$/gm, "");
    const output = await readFile(new URL(filename, directory), "utf8");
    assert.equal(output, expected);
    assert.doesNotThrow(() => new Script(output));
  }
});

test("normal profile keeps its identity and zero ports; MIDI profile is explicit and distinct", async () => {
  const definitions: unknown[][] = [];
  for (const midi of [false, true]) {
    const ports: number[][] = [];
    const versions: number[] = [];
    const context: Record<string, unknown> = {
      loadAPI: (version: number) => versions.push(version),
      host: {
        defineController: (...args: unknown[]) => definitions.push(args),
        defineMidiPorts: (...args: number[]) => ports.push(args),
      },
    };
    const output = await readFile(new URL(midi ? "BeatTwinMidi.control.js" : "BeatTwin.control.js", directory), "utf8");
    runInNewContext(output, context);
    assert.deepEqual(versions, [15]);
    assert.deepEqual(ports, midi ? [[1, 0]] : []);
    assert.equal(context.midiProfileEnabled, midi);
    assert.equal(typeof context.initMidi, "function");
  }
  assert.equal(definitions[0][1], "Beat Twin");
  assert.equal(definitions[0][3], "761be710-90df-4577-8094-01314323214c");
  assert.equal(definitions[1][1], "Beat Twin MIDI");
  assert.notEqual(definitions[1][3], definitions[0][3]);
});
