// GENERATED by scripts/build-bridge.ts; edit the TypeScript source.
// @ts-nocheck
// Source for the Bitwig JS-only controller; build with pnpm build:bridge.
loadAPI(10);

host.defineController("Beat Twin", "Beat Twin", "0.1", "761be710-90df-4577-8094-01314323214c", "Laurent Huzard");

var transport;
var application;
var trackBank;
var sceneBank;
var cursorTrack;
var cursorDevice;
var cursorClip;
var boundedCursorClip;
var inspectionClip;
var inspectionTrack;
var inspectionSlot;
var inspectionVersion = 0;
var inspectionSettledVersion = -1;
var inspectionFlushedVersion = -1;
var remoteControlsBank;
var deviceBanks = [];
var targetTracks = [];
var targetSlots = [];
var popupBrowser;
var browserResultBank;
var bridgeConnection = null;
var bridgeExiting = false;
var controllerInstanceId;
var cursorClipTrack;
var cursorClipSlot;
var targetGeneration = 0;
var lastTargetSignature = null;
var bankNavigation = null;

var BRIDGE_PROTOCOL_VERSION = "beat-twin-bitwig-v2";
var TARGET_GRID_STEPS = 64;
var TARGET_STEP_SIZE_BEATS = 0.25;

// Connection state
var isConnected = false;

function init() {
  transport = host.createTransport();

  // Mark values we need to read as interested
  transport.tempo().value().markInterested();
  transport.getPosition().markInterested();
  transport.isPlaying().markInterested();
  transport.isArrangerRecordEnabled().markInterested();

  application = host.createApplication();
  application.projectName().markInterested();

  controllerInstanceId = createControllerInstanceId();

  // --- Track Control Setup ---
  // Create a Cursor Track (follows selection)
  cursorTrack = host.createCursorTrack("MCP_CURSOR", "Cursor Track", 0, 0, true);

  // Mark interested for Cursor Track
  cursorTrack.volume().markInterested();
  cursorTrack.pan().markInterested();
  cursorTrack.mute().markInterested();
  cursorTrack.solo().markInterested();
  cursorTrack.arm().markInterested();
  cursorTrack.name().markInterested();

  // --- Cursor Clip Setup ---
  // Gives MCP a focused step sequencer surface for writing note steps into the
  // currently selected clip.
  cursorClip = host.createCursorClip(16, 128);
  cursorClip.getLoopLength().markInterested();
  cursorClip.getLoopStart().markInterested();
  cursorClip.getPlayStart().markInterested();
  cursorClip.getPlayStop().markInterested();
  cursorClip.playingStep().markInterested();

  // This private read cursor is anchored once. Read requests never move a
  // viewport or selection, so getStep cannot accidentally read a previous page.
  inspectionClip = host.createLauncherCursorClip(TARGET_GRID_STEPS, 128);
  inspectionClip.setStepSize(TARGET_STEP_SIZE_BEATS);
  inspectionClip.scrollToStep(0);
  inspectionClip.scrollToKey(0);
  inspectionTrack = inspectionClip.getTrack();
  inspectionSlot = inspectionClip.clipLauncherSlot();
  var inspectionValues = [inspectionClip.exists(), inspectionClip.getLoopLength(),
    inspectionTrack.exists(), inspectionTrack.position(), inspectionSlot.exists(),
    inspectionSlot.sceneIndex(), inspectionSlot.hasContent(), application.projectName()];
  for (var readIndex = 0; readIndex < inspectionValues.length; readIndex++) {
    inspectionValues[readIndex].markInterested();
    inspectionValues[readIndex].addValueObserver(invalidateInspection);
  }
  inspectionClip.addNoteStepObserver(invalidateInspection);

  // Agent-mode writes use a dedicated cursor clip so the historical MCP note
  // tools cannot shift its step/key viewport behind the adapter's back.
  boundedCursorClip = host.createLauncherCursorClip(TARGET_GRID_STEPS, 128);
  boundedCursorClip.setStepSize(TARGET_STEP_SIZE_BEATS);
  boundedCursorClip.exists().markInterested();
  boundedCursorClip.getLoopLength().markInterested();

  cursorClipTrack = boundedCursorClip.getTrack();
  cursorClipTrack.exists().markInterested();
  cursorClipTrack.position().markInterested();
  cursorClipTrack.name().markInterested();

  cursorClipSlot = boundedCursorClip.clipLauncherSlot();
  cursorClipSlot.exists().markInterested();
  cursorClipSlot.sceneIndex().markInterested();
  cursorClipSlot.name().markInterested();
  cursorClipSlot.hasContent().markInterested();

  application.projectName().addValueObserver(refreshTargetGeneration);
  cursorClipTrack.exists().addValueObserver(refreshTargetGeneration);
  cursorClipTrack.position().addValueObserver(refreshTargetGeneration);
  cursorClipSlot.exists().addValueObserver(refreshTargetGeneration);
  cursorClipSlot.sceneIndex().addValueObserver(refreshTargetGeneration);

  cursorClip.addStepDataObserver(function (x, y, state) {
    if (isConnected) {
      // Step events are currently only visible in Bitwig's controller log; the
      // Node bridge ignores unsolicited messages unless they match a request id.
      println("Beat Twin clip.step_update " + JSON.stringify({ x: x, y: y, state: state }));
    }
  });

  cursorClip.addPlayingStepObserver(function (step) {
    if (isConnected) {
      println("Beat Twin clip.play_step " + step);
    }
  });

  // --- Cursor Device Setup ---
  cursorDevice = cursorTrack.createCursorDevice("MCP_DEVICE", "Cursor Device", 0, CursorDeviceFollowMode.FOLLOW_SELECTION);
  cursorDevice.name().markInterested();
  cursorDevice.isWindowOpen().markInterested();
  cursorDevice.isExpanded().markInterested();
  
  // Remote Controls (8 knobs/macros)
  remoteControlsBank = cursorDevice.createCursorRemoteControlsPage(8);
  for (var i = 0; i < 8; i++) {
    var param = remoteControlsBank.getParameter(i);
    param.name().markInterested();
    param.value().markInterested();
    param.setIndication(true);
  }

  // Create Main Track Bank (8 tracks, 0 sends, 8 scenes)
  trackBank = host.createMainTrackBank(8, 0, 8);
  trackBank.itemCount().markInterested();
  trackBank.scrollPosition().markInterested();
  trackBank.scrollPosition().addValueObserver(observeBankNavigationPosition);
  trackBank.canScrollForwards().markInterested();
  trackBank.canScrollBackwards().markInterested();

  // Mark interested for Track Bank
  for (var i = 0; i < 8; i++) {
    var track = trackBank.getItemAt(i);
    track.exists().markInterested();
    track.position().markInterested();
    track.volume().markInterested();
    track.pan().markInterested();
    track.mute().markInterested();
    track.solo().markInterested();
    track.arm().markInterested();
    track.name().markInterested();
    track.color().markInterested();
    track.exists().addValueObserver(refreshTargetGeneration);
    track.position().addValueObserver(refreshTargetGeneration);
    targetTracks.push(track);
    targetSlots.push([]);

    var deviceBank = track.createDeviceBank(8);
    for (var d = 0; d < 8; d++) {
      var device = deviceBank.getItemAt(d);
      device.exists().markInterested();
      device.name().markInterested();
      device.isEnabled().markInterested();
    }
    deviceBanks.push(deviceBank);
    
    // Clip Launcher Slots
    var clipLauncher = track.clipLauncherSlotBank();
    for (var j = 0; j < 8; j++) {
      var slot = clipLauncher.getItemAt(j);
      slot.exists().markInterested();
      slot.sceneIndex().markInterested();
      slot.name().markInterested();
      slot.hasContent().markInterested();
      slot.isSelected().markInterested();
      slot.isPlaying().markInterested();
      slot.isRecording().markInterested();
      slot.isPlaybackQueued().markInterested();
      slot.exists().addValueObserver(refreshTargetGeneration);
      slot.sceneIndex().addValueObserver(refreshTargetGeneration);
      slot.isSelected().addValueObserver(refreshTargetGeneration);
      targetSlots[i].push(slot);
    }
  }
  
  // Create Scene Bank (8 scenes)
  sceneBank = host.createSceneBank(8);
  for (var i = 0; i < 8; i++) {
     var scene = sceneBank.getScene(i);
     scene.exists().markInterested();
     scene.name().markInterested();
     scene.sceneIndex().markInterested();
  }

  // --- Popup Browser Setup ---
  popupBrowser = host.createPopupBrowser();
  popupBrowser.exists().markInterested();
  popupBrowser.title().markInterested();
  popupBrowser.contentTypeNames().markInterested();
  popupBrowser.selectedContentTypeIndex().markInterested();
  popupBrowser.selectedContentTypeName().markInterested();
  browserResultBank = popupBrowser.resultsColumn().createItemBank(32);
  for (var r = 0; r < 32; r++) {
    var browserItem = browserResultBank.getItemAt(r);
    browserItem.exists().markInterested();
    browserItem.name().markInterested();
    browserItem.isSelected().markInterested();
  }

  println("Beat Twin Initialized");

  connectLocalBridge();
}

// Bitwig exposes no listen-address or peer-address API. Never open a listener.
// Poll while disconnected: Bitwig may log a failed attempt without a callback.
function connectLocalBridge() {
  if (bridgeExiting) return;
  host.scheduleTask(connectLocalBridge, 2000);
  if (bridgeConnection) return;
  try {
  host.connectToRemoteHost("127.0.0.1", 8889, function (remoteConnection) {
    if (bridgeExiting || bridgeConnection) {
      if (remoteConnection) remoteConnection.disconnect();
      return;
    }
    if (!remoteConnection) return;
    bridgeConnection = remoteConnection;
    isConnected = true;
    var receiveBuffer = "";
    var bridgeSession = { authenticated: true };
    remoteConnection.setDisconnectCallback(function () {
      bridgeConnection = null;
      isConnected = false;
      receiveBuffer = "";
      bridgeSession.authenticated = false;
    });
    remoteConnection.setReceiveCallback(function (data) {
      receiveBuffer += bytesToString(data);
      receiveBuffer = drainReceiveBuffer(receiveBuffer, remoteConnection, bridgeSession);
    });
  });
  } catch (connectionError) {
    // The relay may start later than Bitwig; the next poll retries connection only.
  }
}

function bytesToString(data) {
  var msgString = "";
  for (var i = 0; i < data.length; i++) {
    msgString += String.fromCharCode(data[i]);
  }
  return msgString;
}

function drainReceiveBuffer(buffer, connection, bridgeSession) {
  while (buffer.length > 0) {
    if (buffer.charAt(0) === "{") {
      try {
        handleRequest(JSON.parse(buffer), connection, bridgeSession);
        return "";
      } catch (rawError) {
        println("Error parsing raw JSON: " + rawError);
        sendError(connection, null, -32700, "Parse error");
        return "";
      }
    }

    if (buffer.length < 4) return buffer;

    var bodyLength = (
      (buffer.charCodeAt(0) << 24) |
      (buffer.charCodeAt(1) << 16) |
      (buffer.charCodeAt(2) << 8) |
      buffer.charCodeAt(3)
    ) >>> 0;

    if (bodyLength < 1 || bodyLength > 1048576) {
      println("Invalid frame length: " + bodyLength);
      sendError(connection, null, -32700, "Parse error");
      return "";
    }

    if (buffer.length < bodyLength + 4) return buffer;

    var body = buffer.substring(4, bodyLength + 4);
    buffer = buffer.substring(bodyLength + 4);

    try {
      handleRequest(JSON.parse(body), connection, bridgeSession);
    } catch (frameError) {
      println("Error parsing framed JSON: " + frameError);
      sendError(connection, null, -32700, "Parse error");
    }
  }

  return buffer;
}

function resolveCursorClipStep(step) {
  var stepNumber = Math.max(0, Math.floor(step));
  var pageStart = Math.floor(stepNumber / 16) * 16;
  cursorClip.scrollToStep(pageStart);
  return stepNumber - pageStart;
}

function invalidParams(message) {
  var err = new Error(message);
  err.jsonrpcCode = -32602;
  return err;
}

function bridgeError(code, message) {
  var err = new Error(message);
  err.jsonrpcCode = code;
  return err;
}

function createControllerInstanceId() {
  return "btw_" + Date.now().toString(36) + "_" + Math.floor(Math.random() * 0x7fffffff).toString(36);
}

function isBridgeReadMethod(method) {
  return method === "ping" ||
    method === "bridge.identity" ||
    method === "target.inspect" ||
    method === "transport.getTempo" ||
    method === "transport.getPosition" ||
    method === "transport.getIsPlaying" ||
    method === "transport.getIsRecording" ||
    method === "project.get_summary" ||
    method === "track.list" ||
    method === "track.get_info" ||
    method === "clip.get_grid" ||
    method === "clip.get_status" ||
    method === "clip.get_notes" ||
    method === "track.bank.get_status" ||
    method === "scene.list" ||
    method === "clip.get_info" ||
    method === "track.selected.get_status" ||
    method === "device.get_status" ||
    method === "device.get_remote_controls" ||
    method === "device.list" ||
    method === "browser.get_status" ||
    method === "browser.list_results";
}

function selectedBankTarget() {
  var selected = null;
  for (var trackIndex = 0; trackIndex < targetTracks.length; trackIndex++) {
    for (var slotIndex = 0; slotIndex < targetSlots[trackIndex].length; slotIndex++) {
      var slot = targetSlots[trackIndex][slotIndex];
      if (!slot.isSelected().get()) {
        continue;
      }
      if (selected !== null) {
        return { ambiguous: true };
      }
      selected = {
        ambiguous: false,
        track: targetTracks[trackIndex],
        slot: slot
      };
    }
  }
  return selected;
}

function currentTargetState() {
  if (bankNavigation !== null) {
    return { available: false, track: null, slot: null, trackPosition: -1, slotSceneIndex: -1 };
  }
  var selected = selectedBankTarget();
  if (selected && selected.ambiguous) {
    return {
      available: false,
      track: null,
      slot: null,
      trackPosition: -1,
      slotSceneIndex: -1
    };
  }
  if (selected) {
    var bankTrackPosition = selected.track.position().get();
    var bankSlotSceneIndex = selected.slot.sceneIndex().get();
    return {
      available: selected.track.exists().get() && selected.slot.exists().get() && bankTrackPosition >= 0 && bankSlotSceneIndex >= 0,
      track: selected.track,
      slot: selected.slot,
      trackPosition: bankTrackPosition,
      slotSceneIndex: bankSlotSceneIndex
    };
  }

  var cursorTrackPosition = cursorClipTrack.position().get();
  var cursorSlotSceneIndex = cursorClipSlot.sceneIndex().get();
  return {
    available: cursorClipTrack.exists().get() && cursorClipSlot.exists().get() && cursorTrackPosition >= 0 && cursorSlotSceneIndex >= 0,
    track: cursorClipTrack,
    slot: cursorClipSlot,
    trackPosition: cursorTrackPosition,
    slotSceneIndex: cursorSlotSceneIndex
  };
}

function boundedCursorMatches(target) {
  return target.available &&
    boundedCursorClip.exists().get() &&
    cursorClipTrack.exists().get() &&
    cursorClipSlot.exists().get() &&
    cursorClipTrack.position().get() === target.trackPosition &&
    cursorClipSlot.sceneIndex().get() === target.slotSceneIndex;
}

function targetSignature() {
  var target = currentTargetState();
  return [
    application.projectName().get(),
    target.available,
    target.trackPosition,
    target.slotSceneIndex
  ].join("|");
}

function refreshTargetGeneration() {
  if (bankNavigation !== null) bankNavigation.version += 1;
  var nextSignature = targetSignature();
  if (lastTargetSignature !== null && nextSignature !== lastTargetSignature) {
    targetGeneration += 1;
  }
  lastTargetSignature = nextSignature;
}

function anchorBoundedGrid() {
  boundedCursorClip.scrollToStep(0);
  boundedCursorClip.scrollToKey(0);
}

function currentTargetBinding() {
  requireSettledBank();
  refreshTargetGeneration();
  var target = currentTargetState();
  return {
    controllerInstanceId: controllerInstanceId,
    projectName: application.projectName().get(),
    trackPosition: target.trackPosition,
    slotSceneIndex: target.slotSceneIndex,
    targetGeneration: targetGeneration
  };
}

function sameTargetBinding(left, right) {
  return left && right &&
    left.controllerInstanceId === right.controllerInstanceId &&
    left.projectName === right.projectName &&
    left.trackPosition === right.trackPosition &&
    left.slotSceneIndex === right.slotSceneIndex &&
    left.targetGeneration === right.targetGeneration;
}

function requireCurrentTarget(binding) {
  if (!binding || typeof binding !== "object") {
    throw invalidParams("Missing target binding");
  }
  var current = currentTargetBinding();
  if (!sameTargetBinding(binding, current)) {
    throw bridgeError(-32003, "Target identity changed; create and confirm a fresh plan");
  }
  var target = currentTargetState();
  if (!target.available) {
    throw bridgeError(-32004, "No stable launcher target is selected");
  }
  return target;
}

function isIntegerInRange(value, minimum, maximum) {
  return typeof value === "number" && isFinite(value) && Math.floor(value) === value && value >= minimum && value <= maximum;
}

function isQuarterBeat(value) {
  return typeof value === "number" && isFinite(value) && value > 0 && Math.abs(value * 4 - Math.round(value * 4)) < 0.0000001;
}

function readTargetNotes(target) {
  if (!target.available || !target.slot.hasContent().get() || !boundedCursorMatches(target)) {
    return [];
  }
  anchorBoundedGrid();
  var notes = [];
  for (var step = 0; step < TARGET_GRID_STEPS; step++) {
    for (var pitch = 0; pitch < 128; pitch++) {
      var note = boundedCursorClip.getStep(0, step, pitch);
      if (String(note.state()) === "NoteOn") {
        notes.push({
          channel: note.channel(),
          step: step,
          pitch: pitch,
          velocity: Math.max(1, Math.min(127, Math.round(note.velocity() * 127))),
          durationBeats: note.duration()
        });
      }
    }
  }
  return notes;
}

function inspectBoundTarget(bridgeSession) {
  var target = currentTargetState();
  var binding = currentTargetBinding();
  var clipExists = boundedCursorMatches(target);
  return {
    protocolVersion: BRIDGE_PROTOCOL_VERSION,
    controllerInstanceId: controllerInstanceId,
    projectName: binding.projectName,
    writeAuthenticated: Boolean(bridgeSession.authenticated),
    target: {
      available: target.available,
      binding: binding,
      trackName: target.available ? target.track.name().get() : "",
      slotName: target.available ? target.slot.name().get() : "",
      hasContent: target.available ? target.slot.hasContent().get() : false,
      clipExists: clipExists,
      clipLengthBeats: clipExists ? boundedCursorClip.getLoopLength().get() : null
    },
    transport: {
      tempoBpm: transport.tempo().value().getRaw(),
      positionBeats: transport.getPosition().get(),
      isPlaying: transport.isPlaying().get()
    },
    grid: {
      stepSizeBeats: TARGET_STEP_SIZE_BEATS,
      maxSteps: TARGET_GRID_STEPS
    },
    notes: target.available ? readTargetNotes(target) : []
  };
}

function isValidTrackIndex(index) {
  return typeof index === "number" && index >= 0 && index < 8 && Math.floor(index) === index;
}

function requireSettledBank() {
  if (bankNavigation !== null) throw bridgeError(-32004, "Track bank navigation is synchronizing; retry after controller updates");
}

function beginBankNavigation(position, destination) {
  requireSettledBank();
  // Revoke confirmed bindings before touching any retargetable host proxy.
  targetGeneration += 1;
  bankNavigation = { from: position, destination: destination, observed: false,
    version: 0, flushedVersion: -1 };
  invalidateInspection();
}

function observeBankNavigationPosition(position) {
  if (bankNavigation === null) return;
  bankNavigation.version += 1;
  bankNavigation.observed = isIntegerInRange(position, 0, 2147483647) &&
    (bankNavigation.destination === null ? position !== bankNavigation.from : position === bankNavigation.destination);
}

function requireBankIndex(index, label) {
  if (!isIntegerInRange(index, 0, 7)) throw invalidParams(label + " must be an integer from 0 to 7");
  return index;
}

function requireExistingTrack(index) {
  requireSettledBank();
  var track = trackBank.getItemAt(requireBankIndex(index, "Track index"));
  if (track.exists().get() !== true || !isIntegerInRange(track.position().get(), 0, 2147483647)) {
    throw bridgeError(-32004, "Track is unavailable in the current bank window");
  }
  return track;
}

function requirePortName(name) {
  if (typeof name !== "string" || name.length < 1 || name.length > 128 ||
      name.trim().length === 0 || /[\x00-\x1f\x7f-\x9f]/.test(name)) {
    throw invalidParams("Name must contain 1 to 128 characters without control characters");
  }
  return name;
}

function inspectTrack(index) {
  requireSettledBank();
  var track = trackBank.getItemAt(requireBankIndex(index, "Track index"));
  var exists = track.exists().get();
  if (typeof exists !== "boolean") throw bridgeError(-32004, "Track state is unavailable");
  var position = track.position().get();
  if (exists && !isIntegerInRange(position, 0, 2147483647)) throw bridgeError(-32004, "Track identity is unavailable");
  return { index: index, exists: exists, position: exists ? position : null,
    name: exists ? track.name().get() : null,
    volume: exists ? track.volume().get() : null, pan: exists ? track.pan().get() : null,
    mute: exists ? track.mute().get() : null, solo: exists ? track.solo().get() : null,
    arm: exists ? track.arm().get() : null,
    color: exists ? { red: track.color().red(), green: track.color().green(), blue: track.color().blue() } : null };
}

function inspectTracks() {
  var tracks = [];
  for (var index = 0; index < 8; index++) tracks.push(inspectTrack(index));
  return tracks;
}

function inspectSlot(trackIndex, slotIndex) {
  requireBankIndex(trackIndex, "Track index");
  requireBankIndex(slotIndex, "Slot index");
  var track = inspectTrack(trackIndex);
  var slot = trackBank.getItemAt(trackIndex).clipLauncherSlotBank().getItemAt(slotIndex);
  var slotExists = slot.exists().get();
  if (typeof slotExists !== "boolean") throw bridgeError(-32004, "Slot state is unavailable");
  var exists = track.exists && slotExists;
  var sceneIndex = slot.sceneIndex().get();
  if (exists && !isIntegerInRange(sceneIndex, 0, 2147483647)) throw bridgeError(-32004, "Slot identity is unavailable");
  var content = exists ? slot.hasContent().get() : false;
  if (typeof content !== "boolean") throw bridgeError(-32004, "Slot content state is unavailable");
  return { trackIndex: trackIndex, trackPosition: track.position, slotIndex: slotIndex,
    slotSceneIndex: exists ? sceneIndex : null, exists: exists, hasContent: content,
    name: exists ? slot.name().get() : null,
    isSelected: exists ? slot.isSelected().get() : false,
    isPlaying: exists ? slot.isPlaying().get() : false,
    isRecording: exists ? slot.isRecording().get() : false,
    isPlaybackQueued: exists ? slot.isPlaybackQueued().get() : false };
}

function inspectScenes() {
  var scenes = [];
  for (var index = 0; index < 8; index++) {
    var scene = sceneBank.getScene(index);
    var exists = scene.exists().get();
    var position = scene.sceneIndex().get();
    if (typeof exists !== "boolean" || (exists && !isIntegerInRange(position, 0, 2147483647))) {
      throw bridgeError(-32004, "Scene state is unavailable");
    }
    scenes.push({ index: index, exists: exists, sceneIndex: exists ? position : null,
      name: exists ? scene.name().get() : null });
  }
  return scenes;
}

function inspectTrackWindow() {
  requireSettledBank();
  var position = trackBank.scrollPosition().get();
  var count = trackBank.itemCount().get();
  if (!isIntegerInRange(position, 0, 2147483647) || !isIntegerInRange(count, 0, 2147483647)) {
    throw bridgeError(-32004, "Track bank position or count is unavailable");
  }
  return { size: 8, scrollPosition: position, trackCount: count };
}

function invalidateInspection() {
  inspectionVersion += 1;
  inspectionSettledVersion = -1;
}

function readInspectionNotes(trackIndex, slotIndex) {
  var slot = inspectSlot(trackIndex, slotIndex);
  if (!slot.exists || !slot.hasContent || slot.isSelected !== true ||
      inspectionClip.exists().get() !== true || inspectionTrack.exists().get() !== true ||
      inspectionSlot.exists().get() !== true || inspectionSlot.hasContent().get() !== true ||
      inspectionTrack.position().get() !== slot.trackPosition ||
      inspectionSlot.sceneIndex().get() !== slot.slotSceneIndex) {
    throw bridgeError(-32004, "Select the requested existing launcher clip and wait for cursor synchronization");
  }
  if (inspectionSettledVersion !== inspectionVersion) {
    throw bridgeError(-32004, "Note inspection is synchronizing; retry after controller updates");
  }
  var length = inspectionClip.getLoopLength().get();
  if (typeof length !== "number" || !isFinite(length) || length <= 0) throw bridgeError(-32004, "Clip length is unavailable");
  var notes = [];
  for (var step = 0; step < TARGET_GRID_STEPS; step++) {
    for (var pitch = 0; pitch < 128; pitch++) {
      var note = inspectionClip.getStep(0, step, pitch);
      if (!note) throw bridgeError(-32004, "Note grid is unavailable");
      var state = String(note.state());
      if (state !== "NoteOn" && state !== "NoteSustain" && state !== "Empty") {
        throw bridgeError(-32004, "Note grid state is unavailable");
      }
      if (state === "NoteOn") {
        var velocity = note.velocity();
        var duration = note.duration();
        if (note.channel() !== 0 || note.x() !== step || note.y() !== pitch ||
            typeof velocity !== "number" || !isFinite(velocity) || velocity < 0 || velocity > 1 ||
            typeof duration !== "number" || !isFinite(duration) || duration <= 0) {
          throw bridgeError(-32004, "Note grid data is unavailable");
        }
        notes.push({ channel: 0, step: step, pitch: pitch,
          velocity: Math.max(1, Math.round(velocity * 127)), durationBeats: duration });
      }
    }
  }
  return { trackIndex: trackIndex, trackPosition: slot.trackPosition, slotIndex: slotIndex,
    slotSceneIndex: slot.slotSceneIndex, clipLengthBeats: length,
    coverage: { startStep: 0, stepCount: TARGET_GRID_STEPS, stepSizeBeats: TARGET_STEP_SIZE_BEATS,
      minPitch: 0, maxPitch: 127, channels: [0], completeClip: false }, notes: notes };
}

function handleRequest(request, connection, bridgeSession) {
  if (!request.method) {
    sendError(connection, request.id, -32600, "Invalid Request");
    return;
  }

  var result;
  try {
    if (
      request.method !== "bridge.authenticate" &&
      !isBridgeReadMethod(request.method) &&
      !bridgeSession.authenticated
    ) {
      throw bridgeError(-32001, "Write authentication is required");
    }

    // During bank retargeting, only bank-independent bridge/transport traffic
    // is safe. This also covers legacy bank-relative mutation handlers.
    if (bankNavigation !== null && request.method !== "ping" &&
        request.method.indexOf("bridge.") !== 0 && request.method.indexOf("transport.") !== 0) {
      requireSettledBank();
    }

    switch (request.method) {
      case "bridge.authenticate":
        bridgeSession.authenticated = true;
        result = {
          authenticated: true,
          authentication: "local-only",
          protocolVersion: BRIDGE_PROTOCOL_VERSION,
          controllerInstanceId: controllerInstanceId
        };
        break;

      case "bridge.identity":
        result = {
          protocolVersion: BRIDGE_PROTOCOL_VERSION,
          controllerInstanceId: controllerInstanceId,
          projectName: application.projectName().get(),
          writeAuthentication: "local-only"
        };
        break;

      case "target.inspect":
        result = inspectBoundTarget(bridgeSession);
        break;

      case "target.set_track_name":
        var renameBinding = request.params && request.params[0];
        var trackName = request.params && request.params[1];
        var renameTarget = requireCurrentTarget(renameBinding);
        if (typeof trackName !== "string" || trackName.length < 1 || trackName.length > 64) {
          throw invalidParams("Track name must contain 1-64 characters");
        }
        renameTarget.track.setName(trackName);
        result = "OK";
        break;

      case "target.set_tempo":
        var tempoBinding = request.params && request.params[0];
        var targetTempoBpm = request.params && request.params[1];
        requireCurrentTarget(tempoBinding);
        if (typeof targetTempoBpm !== "number" || !isFinite(targetTempoBpm) || targetTempoBpm < 40 || targetTempoBpm > 240) {
          throw invalidParams("Tempo must be between 40 and 240 BPM");
        }
        transport.tempo().value().setRaw(targetTempoBpm);
        result = "OK";
        break;

      case "target.create_clip":
        var createBinding = request.params && request.params[0];
        var targetLengthBeats = request.params && request.params[1];
        var createTarget = requireCurrentTarget(createBinding);
        if (!isIntegerInRange(targetLengthBeats, 1, 16)) {
          throw invalidParams("Clip length must be an integer from 1 to 16 beats");
        }
        if (createTarget.slot.hasContent().get()) {
          throw bridgeError(-32005, "Target launcher slot is not empty");
        }
        createTarget.slot.createEmptyClip(targetLengthBeats);
        result = "OK";
        break;

      case "target.set_note":
        var noteBinding = request.params && request.params[0];
        var noteStep = request.params && request.params[1];
        var notePitch = request.params && request.params[2];
        var noteVelocity = request.params && request.params[3];
        var noteDuration = request.params && request.params[4];
        var noteTarget = requireCurrentTarget(noteBinding);
        if (!noteTarget.slot.hasContent().get() || !boundedCursorMatches(noteTarget)) {
          throw bridgeError(-32006, "Target launcher clip is unavailable");
        }
        if (!isIntegerInRange(noteStep, 0, TARGET_GRID_STEPS - 1)) {
          throw invalidParams("Note step must be an integer from 0 to 63");
        }
        if (!isIntegerInRange(notePitch, 0, 127)) {
          throw invalidParams("Note pitch must be an integer from 0 to 127");
        }
        if (!isIntegerInRange(noteVelocity, 1, 127)) {
          throw invalidParams("Note velocity must be an integer from 1 to 127");
        }
        if (!isQuarterBeat(noteDuration) || noteStep * TARGET_STEP_SIZE_BEATS + noteDuration > boundedCursorClip.getLoopLength().get()) {
          throw invalidParams("Note duration must be quarter-beat aligned and stay inside the clip");
        }
        anchorBoundedGrid();
        boundedCursorClip.setStep(0, noteStep, notePitch, noteVelocity, noteDuration);
        result = "OK";
        break;

      case "target.clear_note":
        var clearBinding = request.params && request.params[0];
        var clearStep = request.params && request.params[1];
        var clearPitch = request.params && request.params[2];
        var clearTarget = requireCurrentTarget(clearBinding);
        if (!clearTarget.slot.hasContent().get() || !boundedCursorMatches(clearTarget)) {
          throw bridgeError(-32006, "Target launcher clip is unavailable");
        }
        if (!isIntegerInRange(clearStep, 0, TARGET_GRID_STEPS - 1) || !isIntegerInRange(clearPitch, 0, 127)) {
          throw invalidParams("Clear target must use a step from 0-63 and pitch from 0-127");
        }
        anchorBoundedGrid();
        boundedCursorClip.clearStep(0, clearStep, clearPitch);
        result = "OK";
        break;

      // --- Transport ---
      case "transport.play":
        transport.play();
        result = "OK";
        break;
      case "transport.stop":
        transport.stop();
        result = "OK";
        break;
      case "transport.restart":
        transport.restart();
        result = "OK";
        break;
      case "transport.record":
        transport.record();
        result = "OK";
        break;
      case "transport.getTempo":
        // Tempo is a bit complex in Bitwig API, usually requires an observer.
        // For immediate sync return, we might need to cache observed values.
        // OR we just return the currently cached value.
        result = transport.tempo().value().getRaw();
        break;
      case "transport.setTempo":
        if (request.params && request.params[0] !== undefined) {
          transport.tempo().value().setRaw(request.params[0]);
          result = "OK";
        } else {
          throw invalidParams("Missing tempo parameter");
        }
        break;
      case "transport.getPosition":
        result = transport.getPosition().get();
        break;
      case "transport.setPosition":
        if (request.params && request.params[0] !== undefined) {
          transport.getPosition().set(request.params[0]);
          result = "OK";
        } else {
          throw invalidParams("Missing position parameter");
        }
        break;
      case "transport.getIsPlaying":
        result = transport.isPlaying().get();
        break;
      case "transport.getIsRecording":
        result = transport.isArrangerRecordEnabled().get();
        break;

      // Bank-local indices are deliberately distinct from absolute project positions.
      case "project.get_summary":
        result = { projectName: application.projectName().get(), bank: inspectTrackWindow(),
          transport: { tempoBpm: transport.tempo().value().getRaw(), positionBeats: transport.getPosition().get(),
            isPlaying: transport.isPlaying().get(), isRecording: transport.isArrangerRecordEnabled().get() },
          tracks: inspectTracks(), scenes: inspectScenes() };
        break;
      case "track.list":
        result = inspectTracks();
        break;
      case "track.get_info":
        result = inspectTrack(request.params && request.params[0]);
        break;
      case "clip.get_status":
        result = inspectSlot(request.params && request.params[0], request.params && request.params[1]);
        break;
      case "clip.get_grid":
        var gridTracks = inspectTracks();
        for (var gridTrack = 0; gridTrack < 8; gridTrack++) {
          gridTracks[gridTrack].slots = [];
          for (var gridSlot = 0; gridSlot < 8; gridSlot++) gridTracks[gridTrack].slots.push(inspectSlot(gridTrack, gridSlot));
        }
        result = { tracks: gridTracks, window: { trackCount: 8, slotCount: 8 }, bank: inspectTrackWindow() };
        break;
      case "clip.get_notes":
        result = readInspectionNotes(request.params && request.params[0], request.params && request.params[1]);
        break;
      case "track.bank.scroll_forward":
      case "track.bank.scroll_backward":
        var navigationWindow = inspectTrackWindow();
        var forward = request.method === "track.bank.scroll_forward";
        var canScroll = forward ? trackBank.canScrollForwards().get() : trackBank.canScrollBackwards().get();
        if (canScroll !== true) throw bridgeError(-32004, "Track bank cannot scroll in this direction");
        beginBankNavigation(navigationWindow.scrollPosition, null);
        if (forward) trackBank.scrollForwards(); else trackBank.scrollBackwards();
        result = "OK";
        break;
      case "track.bank.scroll_to_position":
        var bankPosition = request.params && request.params[0];
        var bankWindow = inspectTrackWindow();
        if (!isIntegerInRange(bankPosition, 0, bankWindow.trackCount - 1)) throw invalidParams("Position must identify an existing project track");
        if (bankPosition !== bankWindow.scrollPosition) {
          beginBankNavigation(bankWindow.scrollPosition, bankPosition);
          trackBank.scrollPosition().set(bankPosition);
        }
        result = "OK";
        break;
      case "track.scroll_into_view":
        var visibleTrack = requireExistingTrack(request.params && request.params[0]);
        visibleTrack.makeVisibleInArranger();
        visibleTrack.makeVisibleInMixer();
        result = "OK";
        break;
      case "track.rename":
        var renameTrack = requireExistingTrack(request.params && request.params[0]);
        renameTrack.name().set(requirePortName(request.params && request.params[1]));
        result = "OK";
        break;
      case "track.set_color":
        var colorTrack = requireExistingTrack(request.params && request.params[0]);
        for (var colorIndex = 1; colorIndex <= 3; colorIndex++) {
          var colorValue = request.params && request.params[colorIndex];
          if (typeof colorValue !== "number" || !isFinite(colorValue) || colorValue < 0 || colorValue > 1) throw invalidParams("Color components must be finite numbers from 0 to 1");
        }
        colorTrack.color().set(request.params[1], request.params[2], request.params[3]);
        result = "OK";
        break;
      case "scene.rename":
        var renameScene = sceneBank.getScene(requireBankIndex(request.params && request.params[0], "Scene index"));
        if (renameScene.exists().get() !== true || !isIntegerInRange(renameScene.sceneIndex().get(), 0, 2147483647)) throw bridgeError(-32004, "Scene is unavailable");
        renameScene.name().set(requirePortName(request.params && request.params[1]));
        result = "OK";
        break;

      // --- Track Bank Control ---
      case "track.bank.get_status":
        var tracks = [];
        for (var i = 0; i < 8; i++) {
          var t = trackBank.getItemAt(i);
          tracks.push({
            index: i,
            name: t.name().get(),
            volume: t.volume().get(),
            pan: t.pan().get(),
            mute: t.mute().get(),
            solo: t.solo().get(),
            arm: t.arm().get(),
            color: {
              red: t.color().red(),
              green: t.color().green(),
              blue: t.color().blue()
            }
          });
        }
        result = tracks;
        break;

      case "track.bank.volume":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          trackBank.getItemAt(request.params[0]).volume().set(request.params[1]);
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      case "track.bank.pan":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          trackBank.getItemAt(request.params[0]).pan().set(request.params[1]);
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      case "track.bank.mute":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          trackBank.getItemAt(request.params[0]).mute().set(request.params[1]);
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      case "track.bank.solo":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          trackBank.getItemAt(request.params[0]).solo().set(request.params[1]);
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      case "track.bank.select":
        if (request.params && request.params[0] !== undefined) {
          trackBank.getItemAt(request.params[0]).selectInMixer();
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      // --- Clip Launcher ---
      case "clip.launch":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          // track index, slot index
          trackBank.getItemAt(request.params[0]).clipLauncherSlotBank().getItemAt(request.params[1]).launch();
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      case "clip.record":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          // track index, slot index
          trackBank.getItemAt(request.params[0]).clipLauncherSlotBank().getItemAt(request.params[1]).record();
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      case "clip.stop":
         if (request.params && request.params[0] !== undefined) {
            // track index
            trackBank.getItemAt(request.params[0]).stop();
            result = "OK";
         } else throw invalidParams("Missing parameters");
         break;

      case "scene.launch":
        if (request.params && request.params[0] !== undefined) {
          sceneBank.getScene(request.params[0]).launch();
          result = "OK";
        } else throw invalidParams("Missing parameters");
        break;

      case "scene.list":
        var scenes = [];
        for (var i = 0; i < 8; i++) {
           var s = sceneBank.getScene(i);
           scenes.push({
             index: i,
             name: s.name().get()
           });
        }
        result = scenes;
        break;

      case "scene.create":
        sceneBank.createScene();
        result = "OK";
        break;

      case "clip.create":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined && request.params[2] !== undefined) {
          // track index, slot index, length in beats
          trackBank.getItemAt(request.params[0]).clipLauncherSlotBank().getItemAt(request.params[1]).createEmptyClip(request.params[2]);
          result = "OK";
        } else throw invalidParams("Missing parameters (trackIndex, slotIndex, length)");
        break;

      case "clip.select_slot":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          var selectSlot = trackBank.getItemAt(request.params[0]).clipLauncherSlotBank().getItemAt(request.params[1]);
          selectSlot.select();
          result = "OK";
        } else throw invalidParams("Missing parameters (trackIndex, slotIndex)");
        break;

      case "clip.show_in_editor":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          var editorSlot = trackBank.getItemAt(request.params[0]).clipLauncherSlotBank().getItemAt(request.params[1]);
          editorSlot.select();
          editorSlot.showInEditor();
          result = "OK";
        } else throw invalidParams("Missing parameters (trackIndex, slotIndex)");
        break;

      case "clip.get_info":
        result = {
          loopLength: cursorClip.getLoopLength().get(),
          loopStart: cursorClip.getLoopStart().get(),
          playStart: cursorClip.getPlayStart().get(),
          playStop: cursorClip.getPlayStop().get(),
          playingStep: cursorClip.playingStep().get()
        };
        break;

      case "clip.set_note":
        if (
          request.params &&
          request.params[0] !== undefined &&
          request.params[1] !== undefined &&
          request.params[2] !== undefined &&
          request.params[3] !== undefined
        ) {
          // step, pitch, velocity, duration
          cursorClip.setStep(0, resolveCursorClipStep(request.params[0]), request.params[1], request.params[2], request.params[3]);
          result = "OK";
        } else throw invalidParams("Missing parameters (step, pitch, velocity, duration)");
        break;

      case "clip.clear_note":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          // step, pitch
          cursorClip.clearStep(0, resolveCursorClipStep(request.params[0]), request.params[1]);
          result = "OK";
        } else throw invalidParams("Missing parameters (step, pitch)");
        break;

      case "clip.toggle_note":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          // step, pitch, velocity
          var toggleVelocity = request.params[2] !== undefined ? request.params[2] : 127;
          cursorClip.toggleStep(resolveCursorClipStep(request.params[0]), request.params[1], toggleVelocity);
          result = "OK";
        } else throw invalidParams("Missing parameters (step, pitch)");
        break;

      // --- Selected Track Control ---
      case "track.selected.get_status":
        result = {
          name: cursorTrack.name().get(),
          volume: cursorTrack.volume().get(),
          pan: cursorTrack.pan().get(),
          mute: cursorTrack.mute().get(),
          solo: cursorTrack.solo().get(),
          arm: cursorTrack.arm().get()
        };
        break;

      case "track.selected.volume":
        if (request.params && request.params[0] !== undefined) {
          cursorTrack.volume().set(request.params[0]);
          result = "OK";
        } else throw invalidParams("Missing parameter");
        break;

      case "track.selected.pan":
        if (request.params && request.params[0] !== undefined) {
          cursorTrack.pan().set(request.params[0]);
          result = "OK";
        } else throw invalidParams("Missing parameter");
        break;

      case "track.selected.mute":
        if (request.params && request.params[0] !== undefined) {
          cursorTrack.mute().set(request.params[0]);
          result = "OK";
        } else throw invalidParams("Missing parameter");
        break;

      case "track.selected.solo":
        if (request.params && request.params[0] !== undefined) {
          cursorTrack.solo().set(request.params[0]);
          result = "OK";
        } else throw invalidParams("Missing parameter");
        break;

      case "track.selected.arm":
        if (request.params && request.params[0] !== undefined) {
          cursorTrack.arm().set(request.params[0]);
          result = "OK";
        } else throw invalidParams("Missing parameter");
        break;

      case "ping":
        result = "pong";
        break;

      case "application.createInstrumentTrack":
        application.createInstrumentTrack(-1); // -1 means add at end
        result = "OK";
        break;
      
      case "application.createAudioTrack":
        application.createAudioTrack(-1);
        result = "OK";
        break;

      // --- Device Control ---
      case "device.get_status":
        result = {
          name: cursorDevice.name().get(),
          isWindowOpen: cursorDevice.isWindowOpen().get(),
          isExpanded: cursorDevice.isExpanded().get()
        };
        break;

      case "device.toggle_window":
        cursorDevice.isWindowOpen().toggle();
        result = "OK";
        break;

      case "device.toggle_expanded":
        cursorDevice.isExpanded().toggle();
        result = "OK";
        break;

      case "device.get_remote_controls":
        var controls = [];
        for (var i = 0; i < 8; i++) {
          var param = remoteControlsBank.getParameter(i);
          controls.push({
            index: i,
            name: param.name().get(),
            value: param.value().get()
          });
        }
        result = controls;
        break;

      case "device.set_remote_control":
        if (request.params && request.params[0] !== undefined && request.params[1] !== undefined) {
          remoteControlsBank.getParameter(request.params[0]).value().set(request.params[1]);
          result = "OK";
        } else throw invalidParams("Missing parameters (index, value)");
        break;

      case "device.page_next":
        remoteControlsBank.selectNextPage(true);
        result = "OK";
        break;

      case "device.page_previous":
        remoteControlsBank.selectPreviousPage(true);
        result = "OK";
        break;

      case "device.list":
        if (request.params && request.params[0] !== undefined) {
          var trackIndex = request.params[0];
          if (!isValidTrackIndex(trackIndex)) throw invalidParams("Invalid trackIndex (expected integer 0-7)");
          var devices = [];
          for (var di = 0; di < 8; di++) {
            var listedDevice = deviceBanks[trackIndex].getItemAt(di);
            if (listedDevice.exists().get()) {
              devices.push({
                index: di,
                name: listedDevice.name().get(),
                enabled: listedDevice.isEnabled().get()
              });
            }
          }
          result = devices;
        } else throw invalidParams("Missing trackIndex parameter");
        break;

      case "device.browse_insert":
        if (request.params && request.params[0] !== undefined) {
          var insertTrackIndex = request.params[0];
          if (!isValidTrackIndex(insertTrackIndex)) throw invalidParams("Invalid trackIndex (expected integer 0-7)");
          var insertPosition = request.params[1] !== undefined ? request.params[1] : 0;
          trackBank.getItemAt(insertTrackIndex).selectInMixer();
          deviceBanks[insertTrackIndex].browseToInsertDevice(insertPosition);
          result = "OK";
        } else throw invalidParams("Missing parameters (trackIndex, position)");
        break;

      case "device.browse_start":
        if (request.params && request.params[0] !== undefined) {
          var startTrackIndex = request.params[0];
          if (!isValidTrackIndex(startTrackIndex)) throw invalidParams("Invalid trackIndex (expected integer 0-7)");
          var startTrack = trackBank.getItemAt(startTrackIndex);
          startTrack.selectInMixer();
          startTrack.startOfDeviceChainInsertionPoint().browse();
          result = "OK";
        } else throw invalidParams("Missing trackIndex parameter");
        break;

      case "device.browse_end":
        if (request.params && request.params[0] !== undefined) {
          var endTrackIndex = request.params[0];
          if (!isValidTrackIndex(endTrackIndex)) throw invalidParams("Invalid trackIndex (expected integer 0-7)");
          var endTrack = trackBank.getItemAt(endTrackIndex);
          endTrack.selectInMixer();
          endTrack.endOfDeviceChainInsertionPoint().browse();
          result = "OK";
        } else throw invalidParams("Missing trackIndex parameter");
        break;

      // --- Browser Control ---
      case "browser.get_status":
        result = {
          exists: popupBrowser.exists().get(),
          title: popupBrowser.title().get(),
          contentTypeNames: popupBrowser.contentTypeNames().get(),
          selectedContentTypeIndex: popupBrowser.selectedContentTypeIndex().get(),
          selectedContentTypeName: popupBrowser.selectedContentTypeName().get()
        };
        break;

      case "browser.list_results":
        var items = [];
        for (var bi = 0; bi < 32; bi++) {
          var item = browserResultBank.getItemAt(bi);
          var name = item.name().get();
          if (item.exists().get() || (name && name.length > 0)) {
            items.push({ index: bi, exists: item.exists().get(), name: name, selected: item.isSelected().get() });
          }
        }
        result = items;
        break;

      case "browser.select_result":
        if (request.params && request.params[0] !== undefined) {
          popupBrowser.selectFirstFile();
          // In Bitwig 5's popup browser, commit() lands on the previous result
          // unless we advance one extra step from the first visible item.
          for (var si = 0; si <= request.params[0]; si++) {
            popupBrowser.selectNextFile();
          }
          result = "OK";
        } else throw invalidParams("Missing index parameter");
        break;

      case "browser.select_first_file":
        popupBrowser.selectFirstFile();
        result = "OK";
        break;

      case "browser.select_next_file":
        popupBrowser.selectNextFile();
        result = "OK";
        break;

      case "browser.select_previous_file":
        popupBrowser.selectPreviousFile();
        result = "OK";
        break;

      case "browser.commit":
        popupBrowser.commit();
        result = "OK";
        break;

      case "browser.cancel":
        popupBrowser.cancel();
        result = "OK";
        break;

      default:
        sendError(connection, request.id, -32601, "Method not found: " + request.method);
        return;
    }

    // Success response
    sendResponse(connection, request.id, result);

  } catch (e) {
    var code = (e && e.jsonrpcCode) ? e.jsonrpcCode : -32603;
    var message = (e && e.message) ? e.message : String(e);
    var prefix = code === -32602 ? "Invalid params: " : "Internal error: ";
    sendError(connection, request.id, code, prefix + message);
  }
}

function sendResponse(connection, id, result) {
  var response = {
    jsonrpc: "2.0",
    id: id,
    result: result
  };
  sendJSON(connection, response);
}

function sendError(connection, id, code, message) {
  var response = {
    jsonrpc: "2.0",
    id: id,
    error: {
      code: code,
      message: message
    }
  };
  sendJSON(connection, response);
}

function sendJSON(connection, data) {
  var str = JSON.stringify(data) + "\n"; // Newline delimiter
  // Convert string to byte array
  // Explicitly converting char codes to Java byte array-like structure if needed, 
  // but Bitwig SDK usually handles string-compatible byte arrays or we use a helper.
  // However, setReceiveCallback gives us raw bytes, send expects raw bytes.

  var bytes = [];
  for (var i = 0; i < str.length; i++) {
    bytes.push(str.charCodeAt(i));
  }
  connection.send(bytes);
}

function flush() {
  if (bankNavigation !== null && bankNavigation.observed) {
    var observedPosition = trackBank.scrollPosition().get();
    var positionMatches = bankNavigation.destination === null ? observedPosition !== bankNavigation.from : observedPosition === bankNavigation.destination;
    if (isIntegerInRange(observedPosition, 0, 2147483647) && positionMatches &&
        bankNavigation.flushedVersion === bankNavigation.version) {
      bankNavigation = null;
      refreshTargetGeneration();
    } else {
      bankNavigation.flushedVersion = bankNavigation.version;
    }
  }
  // Require two completed update cycles without identity/note changes. A read
  // never initiates scrolling and never guesses that pending data is empty.
  if (inspectionFlushedVersion === inspectionVersion) inspectionSettledVersion = inspectionVersion;
  inspectionFlushedVersion = inspectionVersion;
}

function exit() {
  bridgeExiting = true;
  if (bridgeConnection) bridgeConnection.disconnect();
  println("Beat Twin Exited");
}
