import { readFileSync, writeFileSync } from "node:fs";
import { stripTypeScriptTypes } from "node:module";

for (const [source, output] of [
  ["index.ts", "index.js"],
  ["bitwig-controller/BeatTwin/BeatTwin.control.ts", "bitwig-controller/BeatTwin/BeatTwin.control.js"],
]) {
  // Controller source intentionally stays ES5-compatible for Bitwig's engine.
  const text = stripTypeScriptTypes(readFileSync(source, "utf8"))
    .replace(/^(#![^\n]*\n)?/, "$1// GENERATED by scripts/build-bridge.ts; edit the TypeScript source.\n");
  writeFileSync(output, text);
}
