import { readFileSync, writeFileSync } from "node:fs";
import { stripTypeScriptTypes } from "node:module";

const banner = "// GENERATED by scripts/build-bridge.ts; edit the TypeScript source.\n";
function generate(source: string) {
  return stripTypeScriptTypes(source).replace(/[\t ]+$/gm, "").replace(/^(#![^\n]*\n)?/, "$1" + banner);
}

// Compute every output before writing any file: a missing module or profile
// marker must fail the build rather than leave a partially updated package.
const directory = "bitwig-controller/BeatTwin/";
const controller = ["BeatTwin.control.ts", "midi.ts", "creative.ts"]
  .map((name) => readFileSync(directory + name, "utf8")).join("\n\n");
const marker = "var midiProfileEnabled = false;";
if (controller.split(marker).length !== 2) throw new Error("Expected exactly one MIDI profile build marker");
const outputs = [
  ["index.js", generate(readFileSync("index.ts", "utf8"))],
  ["lib/ear-client.js", generate(readFileSync("lib/ear-client.ts", "utf8"))],
  [directory + "BeatTwin.control.js", generate(controller)],
  [directory + "BeatTwinMidi.control.js", generate(controller.replace(marker, "var midiProfileEnabled = true;"))],
];
for (const [output, contents] of outputs) writeFileSync(output, contents);
