import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, symlinkSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const root = process.cwd();
const temporary = mkdtempSync(join(tmpdir(), "beat-twin-distribution-"));
let transport: StdioClientTransport | undefined;
let timer: ReturnType<typeof setTimeout> | undefined;
try {
  const packed = JSON.parse(execFileSync("npm", ["pack", "--ignore-scripts", "--json", "--pack-destination", temporary], {
    cwd: root, encoding: "utf8", timeout: 30_000,
  })) as Array<{ filename: string; files: Array<{ path: string }> }>;
  assert.equal(packed.length, 1);
  const paths = new Set(packed[0].files.map(file => file.path));
  for (const file of ["index.js", "index.ts", "bitwig-controller/BeatTwin/BeatTwin.control.js",
    "bitwig-controller/BeatTwin/BeatTwin.control.ts", "scripts/mcp-diagnostics.js", "scripts/read-only-smoke.js", "docs/BITWIG_MCP_PORT.md", "docs/BITWIG_MCP_PARITY.md", "docs/BITWIG_MCP_CONSTRUCTION.md", "docs/BITWIG_MCP_TRANSPORT.md", "docs/BITWIG_MCP_MIX.md", "docs/BITWIG_MCP_PARITY_NEXT.md", "docs/BITWIG_CONTROLLER_API_COVERAGE.md", "README.md", "package.json"]) {
    assert.ok(paths.has(file), `Missing distribution artifact: ${file}`);
  }
  assert.ok(![...paths].some(path => /(^|\/)(?:node_modules|\.env|test-results)(?:\/|$)/.test(path)));
  execFileSync("tar", ["-xzf", join(temporary, packed[0].filename), "-C", temporary], { timeout: 10_000 });
  const extracted = join(temporary, "package");
  symlinkSync(resolve(root, "node_modules"), join(extracted, "node_modules"), "dir");
  for (const file of ["index.js", "bitwig-controller/BeatTwin/BeatTwin.control.js"]) {
    assert.match(readFileSync(join(extracted, file), "utf8"), /GENERATED by scripts\/build-bridge.ts/);
  }
  const manifest = JSON.parse(readFileSync(join(extracted, "package.json"), "utf8"));
  assert.equal(manifest.bin["beat-twin"], "./index.js");
  const client = new Client({ name: "distribution-smoke", version: "1.0.0" });
  transport = new StdioClientTransport({ command: process.execPath, args: [join(extracted, "index.js")], cwd: extracted,
    env: { BITWIG_MCP_ENABLE_WRITES: "", BITWIG_MCP_WRITE_POLICY: "", BITWIG_MCP_TOOL_DISCOVERY: "" }, stderr: "pipe" });
  await Promise.race([
    (async () => {
      await client.connect(transport!);
      const result = await client.listTools();
      assert.equal(result.tools.length, 37);
      assert.deepEqual(result.tools.map(tool => tool.name).sort(), [
        "bitwig_session_inspect", "bitwig_arrangement_plan", "transport_get_tempo", "transport_get_position",
        "transport_playing_status", "track_bank_get_status", "scene_list", "clip_get_info",
        "track_selected_get_status", "device_get_status", "device_get_remote_controls", "device_list",
        "browser_get_status", "browser_list_results",
        "project_get_summary", "track_list", "track_get_info", "clip_get_grid", "clip_get_status", "clip_get_notes",
        "clip_get_color", "transport_get_recording_status",
        "transport_get_punch_status", "transport_get_overdub_status", "arranger_get_status", "arranger_cues_list",
        "cursor_track_get_status", "cursor_device_get_status", "cursor_clip_get_status", "mixer_get_master_volume", "mixer_get_send_level", "mixer_return_list",
        "application_get_status", "arranger_get_cue_markers", "drumpad_get_status", "groove_get_status", "project_get_status",
      ].sort());
      assert.ok(result.tools.some(tool => tool.name === "bitwig_session_inspect"));
      // No tools/call: discovery never opens the controller connection.
      console.log(JSON.stringify({ status: "passed", packedArtifacts: paths.size, readOnlyTools: result.tools.length, dawCalls: 0 }));
    })(),
    new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error("Packed MCP startup timed out")), 10_000); }),
  ]);
} finally {
  if (timer) clearTimeout(timer);
  await transport?.close();
  rmSync(temporary, { recursive: true, force: true });
}
